// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: log_record.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Record:
	//	*LogRecord_WriteRecord
	//	*LogRecord_ReadRecord
	//	*LogRecord_QueryRecord
	Record    isLogRecord_Record     `protobuf_oneof:"record"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id        string                 `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *LogRecord) Reset() {
	*x = LogRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_log_record_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRecord) ProtoMessage() {}

func (x *LogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_log_record_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRecord.ProtoReflect.Descriptor instead.
func (*LogRecord) Descriptor() ([]byte, []int) {
	return file_log_record_proto_rawDescGZIP(), []int{0}
}

func (m *LogRecord) GetRecord() isLogRecord_Record {
	if m != nil {
		return m.Record
	}
	return nil
}

func (x *LogRecord) GetWriteRecord() *WriteRecord {
	if x, ok := x.GetRecord().(*LogRecord_WriteRecord); ok {
		return x.WriteRecord
	}
	return nil
}

func (x *LogRecord) GetReadRecord() *ReadRecord {
	if x, ok := x.GetRecord().(*LogRecord_ReadRecord); ok {
		return x.ReadRecord
	}
	return nil
}

func (x *LogRecord) GetQueryRecord() *QueryRecord {
	if x, ok := x.GetRecord().(*LogRecord_QueryRecord); ok {
		return x.QueryRecord
	}
	return nil
}

func (x *LogRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type isLogRecord_Record interface {
	isLogRecord_Record()
}

type LogRecord_WriteRecord struct {
	WriteRecord *WriteRecord `protobuf:"bytes,1,opt,name=writeRecord,proto3,oneof"`
}

type LogRecord_ReadRecord struct {
	ReadRecord *ReadRecord `protobuf:"bytes,2,opt,name=readRecord,proto3,oneof"`
}

type LogRecord_QueryRecord struct {
	QueryRecord *QueryRecord `protobuf:"bytes,3,opt,name=queryRecord,proto3,oneof"`
}

func (*LogRecord_WriteRecord) isLogRecord_Record() {}

func (*LogRecord_ReadRecord) isLogRecord_Record() {}

func (*LogRecord_QueryRecord) isLogRecord_Record() {}

type WriteRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid       string     `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	BucketId  uint32     `protobuf:"varint,2,opt,name=bucketId,proto3" json:"bucketId,omitempty"`
	Size      uint32     `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Signature *Signature `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *WriteRecord) Reset() {
	*x = WriteRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_log_record_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRecord) ProtoMessage() {}

func (x *WriteRecord) ProtoReflect() protoreflect.Message {
	mi := &file_log_record_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRecord.ProtoReflect.Descriptor instead.
func (*WriteRecord) Descriptor() ([]byte, []int) {
	return file_log_record_proto_rawDescGZIP(), []int{1}
}

func (x *WriteRecord) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *WriteRecord) GetBucketId() uint32 {
	if x != nil {
		return x.BucketId
	}
	return 0
}

func (x *WriteRecord) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *WriteRecord) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ReadRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid      string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	BucketId uint32 `protobuf:"varint,2,opt,name=bucketId,proto3" json:"bucketId,omitempty"`
}

func (x *ReadRecord) Reset() {
	*x = ReadRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_log_record_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRecord) ProtoMessage() {}

func (x *ReadRecord) ProtoReflect() protoreflect.Message {
	mi := &file_log_record_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRecord.ProtoReflect.Descriptor instead.
func (*ReadRecord) Descriptor() ([]byte, []int) {
	return file_log_record_proto_rawDescGZIP(), []int{2}
}

func (x *ReadRecord) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ReadRecord) GetBucketId() uint32 {
	if x != nil {
		return x.BucketId
	}
	return 0
}

type QueryRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query *Query `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *QueryRecord) Reset() {
	*x = QueryRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_log_record_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRecord) ProtoMessage() {}

func (x *QueryRecord) ProtoReflect() protoreflect.Message {
	mi := &file_log_record_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRecord.ProtoReflect.Descriptor instead.
func (*QueryRecord) Descriptor() ([]byte, []int) {
	return file_log_record_proto_rawDescGZIP(), []int{3}
}

func (x *QueryRecord) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

var File_log_record_proto protoreflect.FileDescriptor

var file_log_record_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6c, 0x6f, 0x67, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfb, 0x01, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x12, 0x33, 0x0a, 0x0b, 0x77, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x48, 0x00, 0x52, 0x0b, 0x77, 0x72, 0x69,
	0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x30, 0x0a, 0x0a, 0x72, 0x65, 0x61, 0x64,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x48, 0x00, 0x52, 0x0a,
	0x72, 0x65, 0x61, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x33, 0x0a, 0x0b, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x48, 0x00, 0x52, 0x0b, 0x71, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12,
	0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x22, 0x7c, 0x0a, 0x0b, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x63, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x22, 0x3a, 0x0a, 0x0a, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x22, 0x2e, 0x0a,
	0x0b, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1f, 0x0a, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62,
	0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x42, 0x05, 0x5a,
	0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_log_record_proto_rawDescOnce sync.Once
	file_log_record_proto_rawDescData = file_log_record_proto_rawDesc
)

func file_log_record_proto_rawDescGZIP() []byte {
	file_log_record_proto_rawDescOnce.Do(func() {
		file_log_record_proto_rawDescData = protoimpl.X.CompressGZIP(file_log_record_proto_rawDescData)
	})
	return file_log_record_proto_rawDescData
}

var file_log_record_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_log_record_proto_goTypes = []interface{}{
	(*LogRecord)(nil),             // 0: pb.LogRecord
	(*WriteRecord)(nil),           // 1: pb.WriteRecord
	(*ReadRecord)(nil),            // 2: pb.ReadRecord
	(*QueryRecord)(nil),           // 3: pb.QueryRecord
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*Signature)(nil),             // 5: pb.Signature
	(*Query)(nil),                 // 6: pb.Query
}
var file_log_record_proto_depIdxs = []int32{
	1, // 0: pb.LogRecord.writeRecord:type_name -> pb.WriteRecord
	2, // 1: pb.LogRecord.readRecord:type_name -> pb.ReadRecord
	3, // 2: pb.LogRecord.queryRecord:type_name -> pb.QueryRecord
	4, // 3: pb.LogRecord.timestamp:type_name -> google.protobuf.Timestamp
	5, // 4: pb.WriteRecord.signature:type_name -> pb.Signature
	6, // 5: pb.QueryRecord.query:type_name -> pb.Query
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_log_record_proto_init() }
func file_log_record_proto_init() {
	if File_log_record_proto != nil {
		return
	}
	file_signature_proto_init()
	file_query_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_log_record_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_log_record_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_log_record_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_log_record_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_log_record_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*LogRecord_WriteRecord)(nil),
		(*LogRecord_ReadRecord)(nil),
		(*LogRecord_QueryRecord)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_log_record_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_log_record_proto_goTypes,
		DependencyIndexes: file_log_record_proto_depIdxs,
		MessageInfos:      file_log_record_proto_msgTypes,
	}.Build()
	File_log_record_proto = out.File
	file_log_record_proto_rawDesc = nil
	file_log_record_proto_goTypes = nil
	file_log_record_proto_depIdxs = nil
}
